# == Schema Information
#
# Table name: article_types
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  kind       :string(255)      not null
#  slug       :string
#
# Indexes
#
#  index_article_types_on_kind  (kind) UNIQUE
#  index_article_types_on_slug  (slug) UNIQUE
#
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/article_types", type: :request do
  
  # ArticleType. As you add validations to ArticleType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ArticleType.create! valid_attributes
      get article_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      article_type = ArticleType.create! valid_attributes
      get article_type_url(article_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_article_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      article_type = ArticleType.create! valid_attributes
      get edit_article_type_url(article_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ArticleType" do
        expect {
          post article_types_url, params: { article_type: valid_attributes }
        }.to change(ArticleType, :count).by(1)
      end

      it "redirects to the created article_type" do
        post article_types_url, params: { article_type: valid_attributes }
        expect(response).to redirect_to(article_type_url(ArticleType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ArticleType" do
        expect {
          post article_types_url, params: { article_type: invalid_attributes }
        }.to change(ArticleType, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post article_types_url, params: { article_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested article_type" do
        article_type = ArticleType.create! valid_attributes
        patch article_type_url(article_type), params: { article_type: new_attributes }
        article_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the article_type" do
        article_type = ArticleType.create! valid_attributes
        patch article_type_url(article_type), params: { article_type: new_attributes }
        article_type.reload
        expect(response).to redirect_to(article_type_url(article_type))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        article_type = ArticleType.create! valid_attributes
        patch article_type_url(article_type), params: { article_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested article_type" do
      article_type = ArticleType.create! valid_attributes
      expect {
        delete article_type_url(article_type)
      }.to change(ArticleType, :count).by(-1)
    end

    it "redirects to the article_types list" do
      article_type = ArticleType.create! valid_attributes
      delete article_type_url(article_type)
      expect(response).to redirect_to(article_types_url)
    end
  end
end
