# == Schema Information
#
# Table name: article_authors
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  author_id  :bigint
#  article_id :bigint
#
# Indexes
#
#  index_article_authors_on_article_id                (article_id)
#  index_article_authors_on_article_id_and_author_id  (article_id,author_id) UNIQUE
#  index_article_authors_on_author_id                 (author_id)
#
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/article_authors", type: :request do
  
  # ArticleAuthor. As you add validations to ArticleAuthor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ArticleAuthor.create! valid_attributes
      get article_authors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      article_author = ArticleAuthor.create! valid_attributes
      get article_author_url(article_author)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_article_author_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      article_author = ArticleAuthor.create! valid_attributes
      get edit_article_author_url(article_author)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ArticleAuthor" do
        expect {
          post article_authors_url, params: { article_author: valid_attributes }
        }.to change(ArticleAuthor, :count).by(1)
      end

      it "redirects to the created article_author" do
        post article_authors_url, params: { article_author: valid_attributes }
        expect(response).to redirect_to(article_author_url(ArticleAuthor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ArticleAuthor" do
        expect {
          post article_authors_url, params: { article_author: invalid_attributes }
        }.to change(ArticleAuthor, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post article_authors_url, params: { article_author: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested article_author" do
        article_author = ArticleAuthor.create! valid_attributes
        patch article_author_url(article_author), params: { article_author: new_attributes }
        article_author.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the article_author" do
        article_author = ArticleAuthor.create! valid_attributes
        patch article_author_url(article_author), params: { article_author: new_attributes }
        article_author.reload
        expect(response).to redirect_to(article_author_url(article_author))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        article_author = ArticleAuthor.create! valid_attributes
        patch article_author_url(article_author), params: { article_author: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested article_author" do
      article_author = ArticleAuthor.create! valid_attributes
      expect {
        delete article_author_url(article_author)
      }.to change(ArticleAuthor, :count).by(-1)
    end

    it "redirects to the article_authors list" do
      article_author = ArticleAuthor.create! valid_attributes
      delete article_author_url(article_author)
      expect(response).to redirect_to(article_authors_url)
    end
  end
end
