# == Schema Information
#
# Table name: characteristic_groups
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#  name       :string(255)      not null
#  title      :string(255)
#  order      :integer          default(0), not null
#  shown      :boolean          default(TRUE), not null
#
# Indexes
#
#  index_characteristic_groups_on_slug  (slug) UNIQUE
#
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/characteristic_groups", type: :request do
  
  # CharacteristicGroup. As you add validations to CharacteristicGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CharacteristicGroup.create! valid_attributes
      get characteristic_groups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      characteristic_group = CharacteristicGroup.create! valid_attributes
      get characteristic_group_url(characteristic_group)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_characteristic_group_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      characteristic_group = CharacteristicGroup.create! valid_attributes
      get edit_characteristic_group_url(characteristic_group)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CharacteristicGroup" do
        expect {
          post characteristic_groups_url, params: { characteristic_group: valid_attributes }
        }.to change(CharacteristicGroup, :count).by(1)
      end

      it "redirects to the created characteristic_group" do
        post characteristic_groups_url, params: { characteristic_group: valid_attributes }
        expect(response).to redirect_to(characteristic_group_url(CharacteristicGroup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CharacteristicGroup" do
        expect {
          post characteristic_groups_url, params: { characteristic_group: invalid_attributes }
        }.to change(CharacteristicGroup, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post characteristic_groups_url, params: { characteristic_group: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested characteristic_group" do
        characteristic_group = CharacteristicGroup.create! valid_attributes
        patch characteristic_group_url(characteristic_group), params: { characteristic_group: new_attributes }
        characteristic_group.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the characteristic_group" do
        characteristic_group = CharacteristicGroup.create! valid_attributes
        patch characteristic_group_url(characteristic_group), params: { characteristic_group: new_attributes }
        characteristic_group.reload
        expect(response).to redirect_to(characteristic_group_url(characteristic_group))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        characteristic_group = CharacteristicGroup.create! valid_attributes
        patch characteristic_group_url(characteristic_group), params: { characteristic_group: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested characteristic_group" do
      characteristic_group = CharacteristicGroup.create! valid_attributes
      expect {
        delete characteristic_group_url(characteristic_group)
      }.to change(CharacteristicGroup, :count).by(-1)
    end

    it "redirects to the characteristic_groups list" do
      characteristic_group = CharacteristicGroup.create! valid_attributes
      delete characteristic_group_url(characteristic_group)
      expect(response).to redirect_to(characteristic_groups_url)
    end
  end
end
