# == Schema Information
#
# Table name: page_statuses
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  status     :string(255)      not null
#  slug       :string
#
# Indexes
#
#  index_page_statuses_on_slug    (slug) UNIQUE
#  index_page_statuses_on_status  (status) UNIQUE
#
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/page_statuses", type: :request do
  
  # PageStatus. As you add validations to PageStatus, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PageStatus.create! valid_attributes
      get page_statuses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      page_status = PageStatus.create! valid_attributes
      get page_status_url(page_status)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_page_status_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      page_status = PageStatus.create! valid_attributes
      get edit_page_status_url(page_status)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PageStatus" do
        expect {
          post page_statuses_url, params: { page_status: valid_attributes }
        }.to change(PageStatus, :count).by(1)
      end

      it "redirects to the created page_status" do
        post page_statuses_url, params: { page_status: valid_attributes }
        expect(response).to redirect_to(page_status_url(PageStatus.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PageStatus" do
        expect {
          post page_statuses_url, params: { page_status: invalid_attributes }
        }.to change(PageStatus, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post page_statuses_url, params: { page_status: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested page_status" do
        page_status = PageStatus.create! valid_attributes
        patch page_status_url(page_status), params: { page_status: new_attributes }
        page_status.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the page_status" do
        page_status = PageStatus.create! valid_attributes
        patch page_status_url(page_status), params: { page_status: new_attributes }
        page_status.reload
        expect(response).to redirect_to(page_status_url(page_status))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        page_status = PageStatus.create! valid_attributes
        patch page_status_url(page_status), params: { page_status: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested page_status" do
      page_status = PageStatus.create! valid_attributes
      expect {
        delete page_status_url(page_status)
      }.to change(PageStatus, :count).by(-1)
    end

    it "redirects to the page_statuses list" do
      page_status = PageStatus.create! valid_attributes
      delete page_status_url(page_status)
      expect(response).to redirect_to(page_statuses_url)
    end
  end
end
