default: &default
  adapter: postgresql
  encoding: unicode

  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { 'renegadebio_development' } %>
  username: <%= ENV.fetch('POSTGRES_USER') { 'renegadebio' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'password' } %>
  host: <%= ENV.fetch('POSTGRES_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('POSTGRES_PORT') { 5432 } %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { 'renegadebio_test' } %>
  username: <%= ENV.fetch('POSTGRES_USER') { 'renegadebio' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'password' } %>
  host: <%= ENV.fetch('POSTGRES_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('POSTGRES_PORT') { 5432 } %>

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %> # Heroku Specific
  sslmode: require
